### ISSUE TITLE
Initial TODOs 

### ISSUE THREAD

**Issue by codebryo** [vuejs/vue-test-utils#4]
I copied over the TODOs from https://github.com/vuejs/vue-test-utils/issues/1#issuecomment-305899792 so it's not necessary to hunt them down in the long thread.

**TODOs**
- [x] ~~Add shallow method~~ 
- [x] ~~Add emit method? In the proposal this is included in trigger, but it's difficult(impossible?) to implement. Not sure if this is needed, as it will be a thin wrapper around vm.$emit.~~ Won't be added in first version,See #6
- [x] ~~Add option to stub components~~
- [x] ~~Finalize VueWrapper interface. Should it call methods on all wrappers, or default to first wrapper?~~ Using find and findAll
- [x] ~~Add context option to support functional components see~~ #12 
- [x] ~~Test find and findAll using functional component with context~~
- [x] ~~Add flow~~
- [x] ~~Add typescript types~~
- [x] ~~Handle empty WrapperArray method calls~~
- [x] ~~Handle ErrorWrapper method calls~~
- [x] ~~Fix some skipped tests copied from avoriaz~~
- [x] Link docs to gitbook
- [x] ~~add deploy script~~
- [x] ~~Update docs format to follow Vue docs style~~
- [x] ~~Improve docs, especially info on WrapperArray~~
- [x] ~~Improve build pipeline. Should dist be included in the source repo?~~
- [x] ~~Add CI tool - travis/ circle~~
- [x] ~~Add [provide option](https://github.com/eddyerburgh/vue-test-utils-proposal/blob/master/API.md#mountcomponent-options) to mount~~
- [x] ~~Add way to add global mixins/plugins/components without polluting global Vue~~. See  #2
- [x] ~~Add ability to test emitted events - although this can be acheived with `wrapper.vm.$on('event', spy)`.~~ Won't be added in first version, See #6
- [x] Add a README
- [x] Link to Documentation in README
- [x] ~~Add option to pass component as stub~~, see #11 
- [x] ~~Add release script~~
- [x] ~~Stub registered global components when running `shallow`~~
- [x] ~~Throw an error about running in a browser if `window` is undefined~~
- [x] ~~Add git pre commit hooks to check commit message matches guidelines~~
- [x] ~~Improve error messages (errors should have format - [vue-test-utils]: error message)~~
- [x] Handle options.instance when stubbing global components in shallow
- [x] ~~Add option to pass array to options.stub~~
- [x] ~~Add children option to pass children to functional components~~
- [x] ~~Set default branch to dev~~
- [x] ~~Remove `npm postinstall` from master/ release branches~~
- [x] ~~Create example projects and link in README~~
- [x] Add guides on setting up vue-test-utils
- [x] ~~Update mount and shallow arguments in documentation~~

**Comment by LinusBorg** [comment]
*(added checkboxes to track progress)*

**Comment by snaptopixel** [comment]
@codebryo @LinusBorg Is anyone working on the typings? I could probably help there if not, just let me know!

**Comment by eddyerburgh** [comment]
@snaptopixel No, would be great if you could make a PR 😄 

If you do, please follow the new commit convention - https://github.com/vuejs/vue/blob/dev/.github/COMMIT_CONVENTION.md

**Comment by Austio** [comment]
Are we ready to publish a Beta of the library?  Someone already has vue-test-utils on npm, should we reach out and see if we could get that package spot or rename this repo to one we can get on npm

**Comment by eddyerburgh** [comment]
@evan has already been in touch with the author. I'm happy to publish a beta once it becomes available

**Comment by codebryo** [comment]
@eddyerburgh do we have a gitbook for the docs under development already? I would like to get started on that, and add a bunch of examples.

**Comment by eddyerburgh** [comment]
There isn't a gitbook that it's hooked up to, but the /docs directory is in the format requried for a gitbook. It even has a `book.json`. All that needs to be done is add gitbooks itself to the project.

It would be great for you to start working on it 👍

**Comment by eddyerburgh** [comment]
@snaptopixel we still need typings, and I haven't got much experience with typescript. Are you still willing to add them?

**Comment by jraller** [comment]
Ensure that the name vue-test-utils is available on npm. Either get https://www.npmjs.com/package/vue-test-utils -> https://github.com/holmescn/vue-test-utils to hand over the name, or pick an alternative project name that isn't already claimed to eliminate long term confusion?

**Comment by eddyerburgh** [comment]
Hi Jason, we do have the name, but since we haven't released the original
package is still on npm. I understand this is causing confusion and hope to
release asap

**Comment by jraller** [comment]
@eddyerburgh for the typings do you have something in mind other than http://definitelytyped.org/guides/contributing.html for how you want that done?

**Comment by eddyerburgh** [comment]
@jraller Yes I think vue-test-utils should be available on DefinitelyTyped 👍

**Comment by jraller** [comment]
@eddyerburgh I'm looking at the bundling portion of http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html as an alternative for the type implementation. This would incur a small overhead for folks who aren't using typescript of one additional line in package.json and one additional file, but for those using typescript they would get the functionality automatically. I'll keep looking into options and see if I can set up a first draft (which could either be added to this project to to DefinitelyTyped).

**Comment by jraller** [comment]
I just found https://github.com/vuejs/vue-test-utils/tree/master/types and am looking at it now. This renders all of my existing comments rather moot.

**Comment by Austio** [comment]
Hey hey, any word on publishing?

**Comment by eddyerburgh** [comment]
Hi Austin,

There are a few things holding us up. Evan has been busy lately, and I'm on
vacation at the moment. There are also a couple of issues the need to be
sorted before publishing - mainly how find and findAll work.

**Comment by Austio** [comment]
Sweet, thanks for update and enjoy vacation, i can probably clear some room to knock out this week if there is consensus

**Comment by eddyerburgh** [comment]
The problem is that there is no consensus. Previously it was decided that find should behave in a certain way, but another issue caused me to rethink the decision - https://github.com/vuejs/vue-test-utils/issues/24

We need more feedback on these two issues - https://github.com/vuejs/vue-test-utils/issues/5, https://github.com/vuejs/vue-test-utils/issues/27

**Comment by jwkicklighter** [comment]
Just checking in since it's bit a little over a month, any updates on publishing?

**Comment by eddyerburgh** [comment]
Evan's reviewing the code this week and we're planning to publish a beta on npm

**Comment by eddyerburgh** [comment]
The todos are complete, and beta is released 🚀
